---
title: "BC_Fish_Biom_Results_Figs"
format: html
editor: visual
---

## newdata ta

```{r}
ta_newdata <- with(brt_bc_fishbiom_v3,
                 data.frame(turf_algae = seq(min(turf_algae),
                                          max(turf_algae),
                                          length = 100)))
```

## newdata ma

```{r}
ma_newdata <- with(brt_bc_fishbiom_v3,
                 data.frame(total_macroalgae = seq(min(total_macroalgae),
                                          max(total_macroalgae),
                                          length = 100)))
```

## newdata hc

```{r}
hc_newdata <- with(brt_bc_fishbiom_v3,
                 data.frame(total_hard_coral = seq(min(total_hard_coral),
                                          max(total_hard_coral),
                                          length = 100)))
```

# TOTAL HERBIVORES

## summary table

```{r}
herbs_b_mod|> as_draws_df() |> 
  dplyr::select(matches("^b_.*")) |> 
  exp() |> # exp to get log-odds scale (crosses 1)
  summarise_draws(median,
                  HDInterval::hdi, 
                  Pl= ~mean(.x < 1),
                  Pg = ~mean(.x > 1))
```

## predict ta

```{r}
crop_ta_pred <- crop_b_mod |> 
  emmeans(~ turf_algae,
          at = ta_newdata, 
          type = "response") |> 
  as.data.frame()
```

## predict ma

```{r}
herb_ma_pred <- herbs_b_mod |> 
  emmeans(~ total_macroalgae, 
          at = ma_newdata, 
          type = "response") |> 
  as.data.frame()
```

## predict hc

```{r}
herb_hc_pred <- herbs_b_mod |> 
  emmeans(~ total_hard_coral, 
          at = hc_newdata, 
          type = "response") |> 
  as.data.frame()
```

### herbs-ta plot

```{r}
crop_ta_pred |> 
  ggplot(aes(y = emmean,
             x = turf_algae)) +
   geom_point(data = brt_bc_fishbiom_v3,
             aes(y = cropper),
             size = 2.5, 
             shape = 21,
             color = "#8AA17D",
             fill = "#8AA17D",
             alpha = 0.3) +
  geom_line(linewidth = 2,
            color = "#8AA17D") +
  geom_ribbon(aes(ymin = lower.HPD,
                  ymax = upper.HPD),
              fill = "#8AA17D",
              color = "#8AA17D",
              alpha = 0.6) +
  theme_classic()
```


### herbs-ma plot

```{r}
herb_ma_pred |> 
  ggplot(aes(y = emmean,
             x = total_macroalgae)) +
   geom_point(data = brt_bc_fishbiom_v3,
             aes(y = total_herbs),
             size = 2.5, 
             shape = 21,
             color = "#8AA17D",
             fill = "#8AA17D",
             alpha = 0.3) +
  geom_line(linewidth = 2,
            color = "#8AA17D") +
  geom_ribbon(aes(ymin = lower.HPD,
                  ymax = upper.HPD),
              fill = "#8AA17D",
              color = "#8AA17D",
              alpha = 0.6) +
  theme_classic()
```

### herbs-hc plot

```{r}
herb_hc_pred |> 
  ggplot(aes(y = emmean,
             x = total_hard_coral)) +
   geom_point(data = brt_bc_fishbiom_v3,
             aes(y = total_herbs),
             size = 2.5, 
             shape = 21,
             color = "#8AA17D",
             fill = "#8AA17D",
             alpha = 0.3) +
  geom_line(linewidth = 2,
            color = "#8AA17D") +
  geom_ribbon(aes(ymin = lower.HPD,
                  ymax = upper.HPD),
              fill = "#8AA17D",
              color = "#8AA17D",
              alpha = 0.6) +
  theme_classic()
```

