---
title: "Benthic_fits"
format: html
editor: visual
---

# load library

```{r}
#| label: libraries
#| output: false
#| eval: true
#| warning: false
#| message: false
#| cache: false

library(tidyverse)
library(rstanarm)
library(brms)
library(coda)
library(bayesplot)
library(DHARMa)
library(emmeans)
library(broom)
library(tidybayes)
library(ggeffects)
library(broom.mixed)
library(bayestestR)
library(see)
library(easystats)
library(patchwork)
library(ggridges)
source("helperFunctions.R")
library(ggimage)
library(iNEXT)
```

# Variables of interest

- total_hard_coral
- total_macroalgae
- turf_algae
- total_octocoral
- rock
- unconsolidated_subs

```{r}
benthic_v2 <- 
  benthic |>
  mutate(Site_recode = factor(Site_recode)) |> 
  select(Depth,
         Site_recode,
         total_hard_coral,
         total_macroalgae,
         total_octocoral,
         turf_algae,
         rock,
         unconsolidated_subs) |> 
  mutate(prop_hc = total_hard_coral / 100,
         prop_ma = total_macroalgae / 100,
         prop_oct = total_octocoral / 100,
         prop_ta = turf_algae / 100,
         prop_rock = rock / 100,
         prop_us = unconsolidated_subs / 100)

glimpse(benthic_v2)
```


# CORAL 

## def formula

```{r}
coral_form <- bf(prop_hc ~ s(Depth) +
                   (1 | Site_recode),
                 family = zero_inflated_beta())
```

## examine data

```{r}
benthic_v2 |> 
  summarise(logit(median(prop_hc)),
            logit(mad(prop_hc)))
```
```{r}
-2.2/-1.7
```


##  get prio

```{r}
get_prior(coral_form, data = benthic_v2)
```

- b, Intercept, phi, sd, sds, zi

## def prior

```{r}
coral_prior <- prior(normal(2.2, 1.7), class = "Intercept") +
  prior(normal(0, 1.3), class = "b") +
  prior(student_t(3, 0 , 1.7), class = "sds") +
  prior(student_t(3, 0, 1.7), class = "sd") +
  prior(gamma(0.01, 0.01), class = "phi") +
  prior(beta(1,1), class = "zi")
```

## fit full model

```{r}
#| cache: TRUE
coral_mod <- brm(coral_form,
                data = benthic_v2,
                prior = coral_prior,
                sample_prior = "yes",
                iter = 10000,
                warmup = 2000,
                chains = 3, 
                cores = 6,
                thin = 5, 
                control = list(adapt_delta = 0.99,
                                 max_treedepth = 20),
                refresh = 0)
```

### MCMC diagnostics

```{r}
coral_mod |> mcmc_plot(type = "trace")
coral_mod |> mcmc_plot(type = "acf_bar")
coral_mod |> mcmc_plot(type = "rhat_hist")
coral_mod |> mcmc_plot(type = "neff_hist")
```

### residuals

```{r}
coral_resids <- make_brms_dharma_res(coral_mod)

# qqplot
coral_resids |> testUniformity()
coral_resids |> plotResiduals(quantreg = FALSE)
```

- Looks good

# MACROALGAE

## def formula

```{r}
ma_form <- bf(prop_ma ~ s(Depth) +
                   (1 | Site_recode),
                 family = zero_inflated_beta())
```

## examine data

```{r}
benthic_v2 |> 
  summarise(logit(median(prop_ma)),
            logit(mad(prop_ma)))
```

```{r}
1.8/1.4
```


## def prior

```{r}
ma_prior <- prior(normal(1.8, 1.4), class = "Intercept") +
  prior(normal(0, 1.3), class = "b") +
  prior(student_t(3, 0 , 1.4), class = "sds") +
  prior(student_t(3, 0, 1.4), class = "sd") +
  prior(gamma(0.01, 0.01), class = "phi") +
  prior(beta(1,1), class = "zi")
```

## fit full model

```{r}
#| cache: TRUE
ma_mod <- brm(ma_form,
                data = benthic_v2,
                prior = ma_prior,
                sample_prior = "yes",
                iter = 10000,
                warmup = 2000,
                chains = 3, 
                cores = 6,
                thin = 5, 
                control = list(adapt_delta = 0.99,
                                 max_treedepth = 20),
                refresh = 0)
```

### MCMC diagnostics

```{r}
ma_mod |> mcmc_plot(type = "trace")
ma_mod |> mcmc_plot(type = "acf_bar")
ma_mod |> mcmc_plot(type = "rhat_hist")
ma_mod |> mcmc_plot(type = "neff_hist")
```

### residuals

```{r}
ma_resids <- make_brms_dharma_res(ma_mod)

ma_resids |> testUniformity()
ma_resids |> plotResiduals(quantreg = FALSE)
```